<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>7.3</LangVersion>
    <UseWindowsForms>true</UseWindowsForms>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <AssemblyName>ZarexLoader</AssemblyName>
    <RootNamespace>ZarexLoader</RootNamespace>
  </PropertyGroup>
</Project>
